sdk:
  - stable
  - pubspec
stages:
  - lint:
      - group:
          - command: dart run tools:buf generate
          - command: dart run tools:license_header .
          - command: dart format .
          - analyze
          - command: "[[ -z $(git status --porcelain | tee >(cat 1>&2)) ]]"
  - test:
      - test: -p chrome
      - test: -p vm
  - license:
      - group:
          - command: dart run tools:license_header ../..
          - command: "[[ -z $(git status --porcelain | tee >(cat 1>&2)) ]]"
