sdk:
  - stable
  - pubspec
os:
  - linux
  - windows
stages:
  - lint:
      - group:
          - command: dart run buf generate
          - command: dart run license_header ../..
          - command: dart format .
          - analyze
          - command: "[[ -z $(git status --porcelain | tee >(cat 1>&2)) ]]"
        os: linux
  - test:
      - test: -p chrome
      - test: -p vm
