name: connect
repository: https://github.com/connectrpc/connect-dart
packages:
  - packages/**
  - examples/**
ide:
  intellij:
    enabled: false
scripts:
  all:
    steps:
      - melos bootstrap
      - melos run generate
      - melos run license-header
      - melos run format
      - melos run lint
      - melos run test
  license-header: dart run ./scripts/license_header.dart .
  format: melos format -- --fix .
  lint: dart analyze
  generate: melos exec -- buf generate
  clean: melos clean
  test:
    steps:
      - melos run test-web
      - melos run test-io
  test-web:
    exec: dart test -p chrome
    packageFilters:
      scope: connectrpc
  test-io:
    exec: dart test -p vm
    packageFilters:
      scope: connectrpc
