name: connect_dart
publish_to: none
environment:
  sdk: ^3.6.0
dev_dependencies:
  lints: ^4.0.0
  melos: ^6.1.0
workspace:
  - packages/conformance
  - packages/connect
  - example/eliza
  - example/web