sdk:
  - stable
  - pubspec
stages:
  - lint:
      - group:
          - command: dart run ../../scripts/buf.dart generate
          - command: dart format .
          - analyze
  - test:
      - test:
