name: example_web
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4
publish_to: none

# Add regular dependencies here.
dependencies:
  web: ^1.0.0
  connectrpc:
    path: ../../packages/connect
  protobuf: '>=3.1.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  lints: ^4.0.0
