name: ci
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: git config --global core.autocrlf false # For windows
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: bufbuild/buf-setup-action@v1.50.0
      - name: pub get
        run: dart pub get
      - name: activate melos
        run: dart pub global activate melos
      - name: all
        run: melos run all
      - name: Check Diff
        # Windows runs powershell, we have to use different commands for that.
        run: ${{ startsWith(matrix.os, 'windows') && 'if (-not ([string]::IsNullOrEmpty((git status --porcelain)))) { git diff; exit 1 }' || '[[ -z $(git status --porcelain | tee /dev/stderr) ]] || exit 1' }}
